# Site settings
title: Zhaocong Yang
email: zyang19@charlotte.edu
description: > # this means to ignore newlines until "baseurl:"
   PhD Candidate specializing in the intersection of AI, VIS, and HCI.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.zyang19.github.io" # the base hostname & protocol for your site
production_url: "https://www.domoritz.de"
github_username: zyang19
permalink: /blog/:year/:month/:title.html

twitter:
  username: zyang19
sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com


avatar: "./assets/img/avatar-icon.png"
round-avatar: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-sitemap
